### ISSUE TITLE
Swift 2.3?

### ISSUE THREAD

**Issue by ekdysis** [jagajithmk/SubmitButton#1]
How does one get this library working with Swift 2.3?

**Comment by jagajithmk** [comment]
Currently this library is implemented in Swift 3, I will add a pod for the Swift vesion 2.3 in the coming days.

**Comment by SwiftisLife** [comment]
Cool, thanks. Feel free to let me know when that happens as I'm working on a project for my job and they won't migrate their codebase to Swift 3.1 as yet as they are still updating their legacy products. Thanks again.

**Comment by ekdysis** [comment]
Is there a way to migrate this codebase to Swift 2.3? I attempted to do so but the module was built in Swift 3.0. Any suggestions would really assist me. 

Kind Regards, 

Alex

**Comment by ekdysis** [comment]
Any luck with the pod for Swift 2.3? @jagajithmk

**Comment by jagajithmk** [comment]
Sorry, I was busy with my work at office so, couldn't get the time to look
into this.

On 14-Feb-2017 7:39 pm, "Alex L." <notifications@github.com> wrote:

Any luck with the pod for Swift 2.3? @jagajithmk
<https://github.com/jagajithmk>

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/jagajithmk/SubmitButton/issues/1#issuecomment-279716337>,
or mute the thread
